[package]
name = "TokenDistributionSpecs"
edition = "2024"

[dependencies.TokenDistribution]
local = "../token-distribution"

[dependencies.Sui]
git = "https://github.com/asymptotic-code/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "next"
override = true

[dependencies.Prover]
git = "https://github.com/asymptotic-code/sui.git"
subdir = "crates/sui-framework/packages/prover"
rev = "next"
override = true

[dependencies.MoveStdlib]
git = "https://github.com/asymptotic-code/sui.git"
subdir = "crates/sui-framework/packages/move-stdlib"
rev = "next"
override = true

[addresses]
token_distribution_specs = "0x0"
