[package]
name = "ProverSpecs"
edition = "2024"

[dependencies.TokenDistribution]
local = "../token-distribution"

[dependencies.Sui]
git = "https://github.com/asymptotic-code/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "next"
override = true

[dependencies.Prover]
git = "https://github.com/asymptotic-code/sui.git"
subdir = "crates/sui-framework/packages/prover"
rev = "next"
override = true

[addresses]
prover_specs = "0x0"
